//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPartsStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityLog
    {
        public int LogId { get; set; }
        public int UserId { get; set; }
        public string ActionType { get; set; }
        public string TableName { get; set; }
        public Nullable<int> RecordId { get; set; }
        public string Description { get; set; }
        public System.DateTime ActionDate { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
