//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPartsStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        public Cars()
        {
            this.Products = new HashSet<Products>();
        }
    
        public int CarId { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public Nullable<int> Year { get; set; }
    
        public virtual ICollection<Products> Products { get; set; }
    }
}
