//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPartsStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public Orders()
        {
            this.OrderItems = new HashSet<OrderItems>();
            this.Returns = new HashSet<Returns>();
        }
    
        public int OrderId { get; set; }
        public int CustomerId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int StatusId { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public int UserId { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual ICollection<OrderItems> OrderItems { get; set; }
        public virtual OrderStatuses OrderStatuses { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<Returns> Returns { get; set; }
    }
}
