//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPartsStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnReasons
    {
        public ReturnReasons()
        {
            this.Returns = new HashSet<Returns>();
        }
    
        public int ReasonId { get; set; }
        public string Reason { get; set; }
    
        public virtual ICollection<Returns> Returns { get; set; }
    }
}
