//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPartsStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Returns
    {
        public Returns()
        {
            this.ReturnItems = new HashSet<ReturnItems>();
        }
    
        public int ReturnId { get; set; }
        public int OrderId { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public int ReasonId { get; set; }
        public Nullable<decimal> RefundAmount { get; set; }
        public int UserId { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual ICollection<ReturnItems> ReturnItems { get; set; }
        public virtual ReturnReasons ReturnReasons { get; set; }
        public virtual Users Users { get; set; }
    }
}
