//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPartsStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockReceivings
    {
        public StockReceivings()
        {
            this.StockReceivingItems = new HashSet<StockReceivingItems>();
        }
    
        public int ReceivingId { get; set; }
        public int SupplierId { get; set; }
        public System.DateTime ReceivingDate { get; set; }
        public int UserId { get; set; }
    
        public virtual ICollection<StockReceivingItems> StockReceivingItems { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        public virtual Users Users { get; set; }
    }
}
