//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPartsStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockReceivingItems
    {
        public int ReceivingItemId { get; set; }
        public int ReceivingId { get; set; }
        public int ProductId { get; set; }
        public int Quantity { get; set; }
        public decimal UnitPrice { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual StockReceivings StockReceivings { get; set; }
    }
}
