//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPartsStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.ActivityLog = new HashSet<ActivityLog>();
            this.Orders = new HashSet<Orders>();
            this.PriceHistory = new HashSet<PriceHistory>();
            this.Returns = new HashSet<Returns>();
            this.StockReceivings = new HashSet<StockReceivings>();
        }
    
        public int UserId { get; set; }
        public string Login { get; set; }
        public string PasswordHash { get; set; }
        public string FullName { get; set; }
        public int RoleId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<ActivityLog> ActivityLog { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ICollection<PriceHistory> PriceHistory { get; set; }
        public virtual ICollection<Returns> Returns { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual ICollection<StockReceivings> StockReceivings { get; set; }
    }
}
